wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1643171302
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.9.6
      5: 0.12.9
      6: 4.15.0
      8:
      - 1
      - 5
